<?php

namespace Database\Seeders;

use App\Models\AdminMenu;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AdminMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $admin = AdminMenu::create([
            'name' => 'Admin',
            'title' => '系统管理',
            'path' => '/admin',
            'component' => 'AdminLayout',
            'route' => 'admin',
            'icon' => '',
            'pid' => 0,
            'type' => 0,
        ]);
        $user = AdminMenu::create([
            'name' => 'AdminUser',
            'title' => '用户管理',
            'path' => 'user',
            'component' => 'admin/user/index',
            'route' => 'user',
            'icon' => '',
            'pid' => $admin->id,
            'type' => 1,
        ]);
        AdminMenu::insert([
            [
                'name' => 'AdminUserList',
                'title' => '用户列表',
                'path' => 'list',
                'component' => '',
                'route' => 'index',
                'icon' => '',
                'pid' => $user->id,
                'type' => 2,
            ],
            [
                'name' => 'AdminUserShow',
                'title' => '查看用户',
                'path' => 'show',
                'component' => '',
                'route' => 'display',
                'icon' => '',
                'pid' => $user->id,
                'type' => 2,
            ],
            [
                'name' => 'AdminUserAdd',
                'title' => '新增用户',
                'path' => 'add',
                'component' => '',
                'route' => 'create',
                'icon' => '',
                'pid' => $user->id,
                'type' => 2,
            ],
            [
                'name' => 'AdminUserMod',
                'title' => '修改用户',
                'path' => 'update',
                'component' => '',
                'route' => 'modify',
                'icon' => '',
                'pid' => $user->id,
                'type' => 2,
            ],
            [
                'name' => 'AdminUserDel',
                'title' => '删除用户',
                'path' => 'del',
                'component' => '',
                'route' => 'delete',
                'icon' => '',
                'pid' => $user->id,
                'type' => 2,
            ],
        ]);

        $role = AdminMenu::create([
            'name' => 'AdminRole',
            'title' => '角色管理',
            'path' => 'role',
            'component' => 'admin/role/index',
            'route' => 'role',
            'icon' => '',
            'pid' => $admin->id,
            'type' => 1,
        ]);
        AdminMenu::insert([
            [
                'name' => 'AdminRoleList',
                'title' => '角色列表',
                'path' => 'list',
                'component' => '',
                'route' => 'index',
                'icon' => '',
                'pid' => $role->id,
                'type' => 2,
            ],
            [
                'name' => 'AdminRoleShow',
                'title' => '查看角色',
                'path' => 'show',
                'component' => '',
                'route' => 'display',
                'icon' => '',
                'pid' => $role->id,
                'type' => 2,
            ],
            [
                'name' => 'AdminRoleAdd',
                'title' => '新增角色',
                'path' => 'add',
                'component' => '',
                'route' => 'create',
                'icon' => '',
                'pid' => $role->id,
                'type' => 2,
            ],
            [
                'name' => 'AdminRoleMod',
                'title' => '修改角色',
                'path' => 'update',
                'component' => '',
                'route' => 'modify',
                'icon' => '',
                'pid' => $role->id,
                'type' => 2,
            ],
            [
                'name' => 'AdminRoleDel',
                'title' => '删除角色',
                'path' => 'del',
                'component' => '',
                'route' => 'delete',
                'icon' => '',
                'pid' => $role->id,
                'type' => 2,
            ],
        ]);

        $menu = AdminMenu::create([
            'name' => 'AdminMenu',
            'title' => '菜单管理',
            'path' => 'menu',
            'component' => 'admin/menu/index',
            'route' => 'menu',
            'icon' => '',
            'pid' => $admin->id,
            'type' => 1,
        ]);
        AdminMenu::insert([
            [
                'name' => 'AdminMenuList',
                'title' => '菜单列表',
                'path' => 'list',
                'component' => '',
                'route' => 'index',
                'icon' => '',
                'pid' => $menu->id,
                'type' => 2,
            ],
            [
                'name' => 'AdminMenuShow',
                'title' => '查看菜单',
                'path' => 'show',
                'component' => '',
                'route' => 'display',
                'icon' => '',
                'pid' => $menu->id,
                'type' => 2,
            ],
            [
                'name' => 'AdminMenuAdd',
                'title' => '新增菜单',
                'path' => 'add',
                'component' => '',
                'route' => 'create',
                'icon' => '',
                'pid' => $menu->id,
                'type' => 2,
            ],
            [
                'name' => 'AdminMenuMod',
                'title' => '修改菜单',
                'path' => 'update',
                'component' => '',
                'route' => 'modify',
                'icon' => '',
                'pid' => $menu->id,
                'type' => 2,
            ],
            [
                'name' => 'AdminMenuDel',
                'title' => '删除菜单',
                'path' => 'del',
                'component' => '',
                'route' => 'delete',
                'icon' => '',
                'pid' => $menu->id,
                'type' => 2,
            ],
        ]);

        $phone = AdminMenu::create([
            'name' => 'Phone',
            'title' => '电话',
            'path' => '/phone',
            'component' => 'AdminLayout',
            'route' => 'phone',
            'redirect' => '/phone/list',
            'icon' => '',
            'pid' => 0,
            'type' => 1,
        ]);
        AdminMenu::insert([
            [
                'name' => 'PhoneList',
                'title' => '电话列表',
                'path' => 'list',
                'component' => 'phone/index',
                'route' => 'index',
                'icon' => '',
                'pid' => $phone->id,
                'type' => 2,
            ],
            [
                'name' => 'PhoneShow',
                'title' => '电话菜单',
                'path' => 'show',
                'component' => '',
                'route' => 'display',
                'icon' => '',
                'pid' => $phone->id,
                'type' => 2,
            ],
            [
                'name' => 'PhoneAdd',
                'title' => '新增电话',
                'path' => 'add',
                'component' => '',
                'route' => 'create',
                'icon' => '',
                'pid' => $phone->id,
                'type' => 2,
            ],
            [
                'name' => 'PhoneMod',
                'title' => '修改电话',
                'path' => 'update',
                'component' => '',
                'route' => 'modify',
                'icon' => '',
                'pid' => $phone->id,
                'type' => 2,
            ],
            [
                'name' => 'PhoneDel',
                'title' => '删除电话',
                'path' => 'del',
                'component' => '',
                'route' => 'delete',
                'icon' => '',
                'pid' => $phone->id,
                'type' => 2,
            ],
            [
                'name' => 'PhoneUp',
                'title' => '上传电话',
                'path' => 'upload',
                'component' => '',
                'route' => 'upload',
                'icon' => '',
                'pid' => $phone->id,
                'type' => 2,
            ],
        ]);

        $member = AdminMenu::create([
            'name' => 'Member',
            'title' => '会员',
            'path' => '/member',
            'component' => 'AdminLayout',
            'route' => 'phone',
            'redirect' => '/member/user',
            'icon' => '',
            'pid' => 0,
            'type' => 0,
        ]);
        $user = AdminMenu::create([
            'name' => 'MemberUser',
            'title' => '会员管理',
            'path' => 'user',
            'component' => 'member/user/index',
            'route' => 'user',
            'icon' => '',
            'pid' => $member->id,
            'type' => 1,
        ]);
        AdminMenu::insert([
            [
                'name' => 'MemberUserList',
                'title' => '会员列表',
                'path' => 'list',
                'component' => '',
                'route' => 'index',
                'icon' => '',
                'pid' => $user->id,
                'type' => 2,
            ],
            [
                'name' => 'MemberUserShow',
                'title' => '显示会员',
                'path' => 'show',
                'component' => '',
                'route' => 'display',
                'icon' => '',
                'pid' => $user->id,
                'type' => 2,
            ],
            [
                'name' => 'MemberUserAdd',
                'title' => '新增会员',
                'path' => 'add',
                'component' => '',
                'route' => 'create',
                'icon' => '',
                'pid' => $user->id,
                'type' => 2,
            ],
            [
                'name' => 'MemberUserMod',
                'title' => '修改会员',
                'path' => 'update',
                'component' => '',
                'route' => 'modify',
                'icon' => '',
                'pid' => $user->id,
                'type' => 2,
            ],
            [
                'name' => 'MemberUserDel',
                'title' => '删除会员',
                'path' => 'del',
                'component' => '',
                'route' => 'delete',
                'icon' => '',
                'pid' => $user->id,
                'type' => 2,
            ],
        ]);
        $tel = AdminMenu::create([
            'name' => 'MemberPhone',
            'title' => '号码薄',
            'path' => 'phone',
            'component' => 'member/phone/index',
            'route' => 'phone',
            'icon' => '',
            'pid' => $member->id,
            'type' => 1,
        ]);
        AdminMenu::insert([
            [
                'name' => 'MemberPhoneList',
                'title' => '号码列表',
                'path' => 'list',
                'component' => '',
                'route' => 'index',
                'icon' => '',
                'pid' => $tel->id,
                'type' => 2,
            ],
            [
                'name' => 'MemberPhoneShow',
                'title' => '显示号码',
                'path' => 'show',
                'component' => '',
                'route' => 'display',
                'icon' => '',
                'pid' => $tel->id,
                'type' => 2,
            ],
            [
                'name' => 'MemberPhoneAdd',
                'title' => '新增号码',
                'path' => 'add',
                'component' => '',
                'route' => 'create',
                'icon' => '',
                'pid' => $tel->id,
                'type' => 2,
            ],
            [
                'name' => 'MemberPhoneMod',
                'title' => '修改号码',
                'path' => 'update',
                'component' => '',
                'route' => 'modify',
                'icon' => '',
                'pid' => $tel->id,
                'type' => 2,
            ],
            [
                'name' => 'MemberPhoneDel',
                'title' => '删除号码',
                'path' => 'del',
                'component' => '',
                'route' => 'delete',
                'icon' => '',
                'pid' => $tel->id,
                'type' => 2,
            ],
        ]);
    }
}
