<?php

namespace App\Admin\Actions;

use App\Models\Phone;
use Dcat\Admin\Actions\Action;
use Dcat\Admin\Actions\Response;
use Dcat\Admin\Traits\HasPermissions;
use Dcat\Admin\Widgets\Table;
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class ShowUserPhones extends Action
{
    /**
     * @return string
     */
	protected $title = '号码表';

    protected $modalId = 'show-current-user';

    /**
     * Handle the action request.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function handle(Request $request)
    {
        // dump($this->getKey());
        $phones = Phone::query()->where('admin_id',\Admin::user()->id)->get();
        $table = Table::make($phones?->toArray());
        return $this->response()->success('查询成功')->html($table);
    }

    public function handleHtmlResponse()
    {
        return <<<'JS'
function(target,html, data){
    var $modal = $(target.data('target'));
    $modal.find('.modaly-body').html(html)
    $modal.modal('show')
}
JS;

    }
    public function setUpHtmlAttributes()
    {
        $this->addHtmlClass('btn btn-primary');
        $this->setHtmlAttribute('data-target','#'.$this->modalId);
        parent::setUpHtmlAttributes(); // TODO: Change the autogenerated stub
    }

    public function html()
    {
        $html = parent::html(); // TODO: Change the autogenerated stub
        return <<<HTML
{$html}
<div class="modal fade" id="{$this->modalId}" tabindex="1-" role="dialog">
<div class="modal-dialog  modal-lg" role="document">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-label="Close">
<span aria-hidden="true">&times;</span></button>
<h4 class="modal-title">{$this->title()}</h4>
</div>
<div class="modal-body"></div>
</div>
</div>
</div>
HTML;

    }


    /**
     * @param Model|Authenticatable|HasPermissions|null $user
     *
     * @return bool
     */
    protected function authorize($user): bool
    {
        return true;
    }

    /**
     * @return array
     */
    protected function parameters()
    {
        return [];
    }
}
